### Laboratory 6: Matrices

# <b>Linear Algebra for CpE

<h5>Coded and Submitted by:
<h5><i>Esguerra, Gian Karl J.<i>
<h5><i>58011<i>

### <b>TASK 1<b>

In [22]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as la

In [23]:
## Function area
def mat_desc(matrix): 
  square = True if matrix.shape[0] == matrix.shape[1] else False 
  empty = matrix.size == 0
  zero_mat_sqr = np.zeros((3,3))
  ones_mat_sqr = np.ones((3,3))
  identity = np.eye(3)
  print(f'Matrix:\n{matrix}','\n'f'Shape:\t{matrix.shape}','\n',f'Size:\t{matrix.size}','\n',f'Rank:\t{matrix.ndim}',
        '\n',f'Square: {square}','\n',f'Empty: {empty}','\n',f'Identity Matrix:\n {identity}','\n',
        f'Ones Matrix:\n {ones_mat_sqr}','\n',f'Zeros Matrix:\n {zero_mat_sqr}')

In [24]:
## Matrix declarations
C = np.array([[2, -4, 6],[2, -1, 4],[9, 2, -1],[1, 3, -7]])
K = np.array([[26, -3, -4],[3, 9, -1],[4, -12, 2],[3, 1, -2]])
S = np.array([[2, -4, 3],[4, -9, 4],[11, 5, -2],[5, 8, -1]])
E = np.array([[9, -5, 6],[9, -13, 18],[5, 7, -9],[6, 8, -12]])
G = np.array([[12, -13, 15],[19, -12, 10],[15, 6, -11],[7, 13, -8]])

In [25]:
## Test Areas
mat_desc(C)
print('\t')
mat_desc(K)
print('\t')
mat_desc(S)
print('\t')
mat_desc(E)
print('\t')
mat_desc(G)

Matrix:
[[ 2 -4  6]
 [ 2 -1  4]
 [ 9  2 -1]
 [ 1  3 -7]] 
Shape:	(4, 3) 
 Size:	12 
 Rank:	2 
 Square: False 
 Empty: False 
 Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 
 Ones Matrix:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]] 
 Zeros Matrix:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
	
Matrix:
[[ 26  -3  -4]
 [  3   9  -1]
 [  4 -12   2]
 [  3   1  -2]] 
Shape:	(4, 3) 
 Size:	12 
 Rank:	2 
 Square: False 
 Empty: False 
 Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 
 Ones Matrix:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]] 
 Zeros Matrix:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
	
Matrix:
[[ 2 -4  3]
 [ 4 -9  4]
 [11  5 -2]
 [ 5  8 -1]] 
Shape:	(4, 3) 
 Size:	12 
 Rank:	2 
 Square: False 
 Empty: False 
 Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 
 Ones Matrix:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]] 
 Zeros Matrix:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
	
Matrix:
[[  9  -5   6]
 [  9 -13  18]
 [  5   7  -9]
 [  6   8 -12]] 
Shape:	(4, 3) 
 Size:	12 
 Rank:	2 
 Square: Fal

### <b>TASK 2<b>

In [48]:
## Function Area 
def isScalarMatrix(mat) : 
    for x in range(0,len(mat[0])) : 
        for y in range(0,len(mat[0])) : 
            if ((x != y) 
            and (mat[x][y] != 0)) : 
                return False
    for x in range(0,len(mat[0])-1) : 
        if (mat[x][x] !=
        mat[x + 1][x + 1]) : 
            return False
    return True
 
def mat_operations(matrix_a, matrix_b):
    try:
      name = ""
      if(isScalarMatrix(matrix_a) and isScalarMatrix(matrix_b)):
          name = "Scalar"
      else:
          name = "Matrix"
      sum = matrix_a + matrix_b
      difference = matrix_a - matrix_b
      product = np.multiply(matrix_a,matrix_b)
      quotient = np.divide(matrix_a,matrix_b)
      print(f'Sum of {name}:\n{sum}','\n',f'Difference of {name}:\n{difference}','\n',f'Product of {name}:\n{product}',
            '\n'f'Product of {name}:\n{product}')
    except:
      print("Matrices are not viable for operations")

In [49]:
## Matrix Declartion
c = np.array([[2, -4, 6],[2, -1, 4],[9, 2, -1],[1, 3, -7]])
k = np.array([[26, -3, -4],[3, 9, -1],[4, -12, 2],[3, 1, -2]])
s = np.array([[2, -4, 3],[4, -9, 4],[11, 5, -2],[5, 8, -1]])
e = np.array([[9, -5, 6],[9, -13, 18],[5, 7, -9],[6, 8, -12]])
g = np.array([[12, -13, 15],[19, -12, 10],[15, 6, -11],[7, 13, -8]])

In [50]:
## Test Area 
mat_operations(c,k)

Sum of Matrix:
[[ 28  -7   2]
 [  5   8   3]
 [ 13 -10   1]
 [  4   4  -9]] 
 Difference of Matrix:
[[-24  -1  10]
 [ -1 -10   5]
 [  5  14  -3]
 [ -2   2  -5]] 
 Product of Matrix:
[[ 52  12 -24]
 [  6  -9  -4]
 [ 36 -24  -2]
 [  3   3  14]] 
Product of Matrix:
[[ 52  12 -24]
 [  6  -9  -4]
 [ 36 -24  -2]
 [  3   3  14]]
