# <b>Linear Algebra for CpE

###<b> Laboratory 6: Matrices

<h5>Coded and Submitted by:<h5>
<h5><i>Esguerra, Gian Karl J.<i>
<h5><i>58011<i>

<b>Lab Exercises:<b>

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as la
%matplotlib inline


1. Given the linear combination below, try to create a corresponding matrix representing it.

$$\theta = 5x + 3y - z$$

In [ ]:
𝜃 = np.array([5, 3, -1])
print("𝜃 =",𝜃 ) 

𝜃 = [ 5  3 -1]


2. Given the system of linear combinations below, try to encode it as a matrix. Also describe the matrix.
$$ A = \left\{\begin{array} 5x_1 + 2x_2 +x_3\\ 4x_2 - x_3\\ 10x_3 \end{array}\right. $$

In [ ]:
def describe_mat(matrix):
    print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\n')
   

In [ ]:
 A = np.array([
    [1, 2, 1],
    [0, 4, -1],
    [0, 0, 10]
])
describe_mat(A)

Matrix:
[[ 1  2  1]
 [ 0  4 -1]
 [ 0  0 10]]

Shape:	(3, 3)
Rank:	2



3. Given the matrix below, express it as a linear combination in a markdown.

In [ ]:
G = np.array([
    [1,7,8],
    [2,2,2],
    [4,6,7]
])
G = np.diag(G)
G

array([1, 2, 7])

4. Given the matrix below display the output as a LaTeX makdown also express it as a system of linear combinations.

In [ ]:
H = np.tril(G)
H

array([[1, 0, 0],
       [1, 2, 0],
       [1, 2, 7]])

$$
H=\begin{bmatrix} 1 & 0 & 0 \\ 1 & 2 & 0 \\ 1 & 2 & 7\end{bmatrix} 
$$<br><br>

$$H= \left\{ \begin{array}\\ x \\  x + 2y \\ x + 2y + 7z \end{array}\right. \\
 $$